### ISSUE TITLE
Marker positioning 

### ISSUE THREAD

**Issue by itggot-joel-eriksson** [the-ccode/cGraph#2]
When hovering over the graph the `marker` is shown to the right of the cursor. At least this is the case on a 1366x768 resolution display. 

> By `marker` I mean the line that shows the value and date of that point. In the below image it shows a value of 46 and the date Sunday 20 March, 2016.

![image](https://cloud.githubusercontent.com/assets/14174732/15456348/c20b830c-206d-11e6-82df-fa374d32f2d2.jpeg) _Image is not representative since it was taken on a higher resolution touch enabled device where this issue is not present._

In conclusion the issue is that the marker in the image above would be shown when the cursor is positioned about 100 pixels to the left of the marker on a 1366x768 resolution display.

**Comment by gustafros** [comment]
I vilken/vilka webbläsare händer detta i? Endast på tablet?

**Comment by itggot-joel-eriksson** [comment]
Det var på en laptop som detta hände med Chrome som webbläsare.
